### ISSUE TITLE
Duplicate Mod error

### ISSUE THREAD

**Issue by Shtwophell** [darkevilmac/MovingWorld#14]
Hello there, I am having this error when using Moving world with Forge essentials

"Encountered an unexpected exception
net.minecraftforge.fml.common.DuplicateModsFoundException:
Duplicate Mods:
darkevilmac.movingworld.common.asm.coremod : /home/Jason122/NN19010770/minecraft.jar
at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:397) ~[Loader.class:?]
at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:359) ~[Loader.class:?]
at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:483) ~[Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355) ~[FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[po.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
"

Is there any way around this?

Thank you for your time

**Comment by darkevilmac** [comment]
See #11
