### ISSUE TITLE
[CRASH ERROR] [1.12.2] Incompatible with Shaders MOD

### ISSUE THREAD

**Issue by darkeshsilva** [darkevilmac/MovingWorld#61]
The mod is with an incopatibility with the optfine shaders. Every time I try to load the world with the shaders turned on it crashes.

**Comment by darkeshsilva** [comment]
```

Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 11/11/18 8:13 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.ActiveRenderInfo.func_178806_a(ActiveRenderInfo.java:57)
	at net.minecraft.client.renderer.ActiveRenderInfo.func_186703_a(ActiveRenderInfo.java:68)
	at net.minecraft.client.renderer.EntityRenderer.func_78481_a(EntityRenderer.java:680)
	at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:933)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:284)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4097)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1592)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by darkeshsilva** [comment]
I've already checked it out and it's only with the movingworld that I have these problems!

I have to disable the shaders to enter the world and then reactivate it.
Ever!

**Comment by darkevilmac** [comment]
It's hard enough making the render code work in it's current state. I'm not going to be adding a bunch of checks to make optifine not crash.
